[monitor://$SPLUNK_HOME/etc/apps/NextGenCDN/samples/sample_cdn_logs.json]
disabled = false
index = cdn
sourcetype = cdn:edge:access

[monitor://$SPLUNK_HOME/etc/apps/NextGenCDN/samples/sample_edge_metrics.json]
disabled = false
index = cdn
sourcetype = cdn:edge:metrics

[monitor://$SPLUNK_HOME/etc/apps/NextGenCDN/samples/sample_origin_performance.json]
disabled = false
index = cdn
sourcetype = cdn:origin:performance

[monitor://$SPLUNK_HOME/etc/apps/NextGenCDN/samples/sample_security_events.json]
disabled = false
index = cdn
sourcetype = cdn:security:events

[monitor://$SPLUNK_HOME/etc/apps/NextGenCDN/samples/sample_user_experience.json]
disabled = false
index = cdn
sourcetype = cdn:user:experience
